# Generated by Django 2.0.4 on 2018-04-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
